# Generated by Django 3.1.2 on 2020-10-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=254)),
                ('contact', models.IntegerField(blank=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField(blank=True)),
                ('initial_diagnosis', models.TextField(blank=True)),
                ('updated_diagnosis', models.TextField(blank=True)),
            ],
        ),
    ]
