# Generated by Django 3.1.2 on 2020-10-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
