# Generated by Django 3.1.2 on 2020-11-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0006_auto_20201028_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='November', max_length=50)),
            ],
        ),
    ]
