# Generated by Django 3.1.2 on 2020-11-03 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0008_auto_20201102_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('month', models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='emr.month')),
            ],
        ),
    ]
