# Generated by Django 3.1.2 on 2020-11-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0010_auto_20201111_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('date_time',)},
        ),
    ]
