# Generated by Django 3.1.2 on 2020-11-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0011_auto_20201111_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
    ]
