# Generated by Django 3.1.2 on 2020-11-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0013_auto_20201118_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
