# Generated by Django 3.1.2 on 2020-11-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0014_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='emr.day'),
            preserve_default=False,
        ),
    ]
