# Generated by Django 3.1.2 on 2020-11-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0015_appointment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='month_number',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='emr.day'),
        ),
    ]
